spring.application.name=Z
# Force the server to read properties files as UTF-8
spring.messages.encoding=UTF-8
spring.web.locale-resolver=accept-header

# Force the server to WRITE the response as UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true